name: OWASP Scan by stable version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: OWASP scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
            target: 'https://www.example.com'
            #rules_file_name: ".zap/gen.conf"
            artifact: 'report.html'
